apiVersion: v1
kind: Service
metadata:
  name: pii-inference
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pii-inference
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.inference.service.type }}
  ports:
    - port: {{ .Values.inference.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: pii-inference
